// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAve4ESFmCP4QCD9JCwCe8Q_cj0sHaoYcA',
    appId: '1:902883106258:web:a1e5bb02b42ba25c88bc0b',
    messagingSenderId: '902883106258',
    projectId: 'buddy-expense-tracker',
    authDomain: 'buddy-expense-tracker.firebaseapp.com',
    storageBucket: 'buddy-expense-tracker.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9VLwSaPxJgl3iyykjsSQHUkXYFACbLRg',
    appId: '1:902883106258:android:f36c2e53e066d5ed88bc0b',
    messagingSenderId: '902883106258',
    projectId: 'buddy-expense-tracker',
    storageBucket: 'buddy-expense-tracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWqaURn53z6mhM7BQeoDoxcwooGQi3CLg',
    appId: '1:902883106258:ios:ee7a96fde21e001888bc0b',
    messagingSenderId: '902883106258',
    projectId: 'buddy-expense-tracker',
    storageBucket: 'buddy-expense-tracker.firebasestorage.app',
    iosBundleId: 'com.example.buddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWqaURn53z6mhM7BQeoDoxcwooGQi3CLg',
    appId: '1:902883106258:ios:ee7a96fde21e001888bc0b',
    messagingSenderId: '902883106258',
    projectId: 'buddy-expense-tracker',
    storageBucket: 'buddy-expense-tracker.firebasestorage.app',
    iosBundleId: 'com.example.buddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAve4ESFmCP4QCD9JCwCe8Q_cj0sHaoYcA',
    appId: '1:902883106258:web:f0d3b9f78ce4253488bc0b',
    messagingSenderId: '902883106258',
    projectId: 'buddy-expense-tracker',
    authDomain: 'buddy-expense-tracker.firebaseapp.com',
    storageBucket: 'buddy-expense-tracker.firebasestorage.app',
  );
}
